name: Release

on:
  push:
    branches:
      - main
      - stage

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install Dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
      - name: Lint
        run: yarn lint
      - run: npx release-it
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
